# Copyright (C) 2021, meta-linux-mainline contributors
# SPDX-License-Identifier: CC0-1.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/frnmst/md-toc
    rev: 8.0.0
    hooks:
    -   id: md-toc
-   repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
    -   id: isort

# Disabled for now:
# -   repo: https://github.com/fsfe/reuse-tool
#     rev: v0.12.1
#     hooks:
#     -   id: reuse
