# Copyright (C) 2021, meta-linux-mainline contributors
# SPDX-License-Identifier: CC0-1.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
    -   id: shellcheck
-   repo: https://github.com/frnmst/md-toc
    rev: 8.1.9
    hooks:
    -   id: md-toc
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

# Disabled for now:
# -   repo: https://github.com/fsfe/reuse-tool
#     rev: v0.12.1
#     hooks:
#     -   id: reuse
