# Copyright (C) 2023, meta-linux-mainline contributors
# SPDX-License-Identifier: MIT

header:
  version: 14

distro: poky
target:
  - core-image-minimal

defaults:
  repos:
    branch: master

repos:
  meta-linux-mainline:

  poky:
    url: https://git.yoctoproject.org/git/poky
    path: layers/poky
    layers:
      meta:
      meta-poky:

bblayers_conf_header:
  base: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  base: |
    PACKAGE_CLASSES ?= "package_rpm"
    SDKMACHINE ?= "x86_64"
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"
    BB_DISKMON_DIRS ?= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
    CONF_VERSION = "2"
  rm_work: |
    INHERIT += "rm_work"
  simplify_build: |
    DISTRO_FEATURES:remove = "ptest"
    PACKAGECONFIG:remove:pn-qemu-system-native = "alsa epoxy virglrenderer"
  oldest_kernel: |
    require conf/linux-mainline/oldest-kernel.inc
  debug_tweaks: |
    EXTRA_IMAGE_FEATURES ?= "empty-root-password allow-empty-password allow-root-login"
