#! /usr/bin/env python3
# Copyright (C) 2021, meta-linux-mainline contributors
# SPDX-License-Identifier: MIT

import argparse
import datetime
import os
import subprocess
import sys

SOURCEPATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))


def pretty_timedelta(t):
    seconds = t.seconds % 60
    minutes = t.total_seconds() // 60
    hours = int(minutes // 60)
    minutes = int(minutes % 60)
    return f"{hours:02d}h {minutes:02d}m {seconds:02d}s"


class Build:
    def __init__(self, buildset, release, machine, kernel):
        self.release = release
        self.machine = machine
        self.kernel = kernel
        self.buildset = buildset
        self.builddir = os.path.join(buildset.workdir, "build")
        self.confdir = os.path.join(self.builddir, "conf")
        self.logpath = os.path.join(
            buildset.logdir, f"build_{self.release}_{self.machine}_{self.kernel}.log"
        )
        self.dl_dir = os.path.join(buildset.workdir, "downloads")
        self.sstate_dir = os.path.join(buildset.workdir, "sstate-cache")

        os.makedirs(self.dl_dir, exist_ok=True)
        os.makedirs(self.sstate_dir, exist_ok=True)

    def skip(self):
        if "riscv" in self.machine:
            if self.release == "dunfell":
                return True
            if self.kernel not in ("lts", "stable", "mainline"):
                kernel_version = tuple([int(s) for s in self.kernel.split(".")])
                if kernel_version < (5, 10):
                    return True
        return False

    def build(self):
        self.buildset.msg(
            f"R={self.release} M={self.machine} K={self.kernel}".ljust(64)
        )
        if self.skip():
            self.buildset.msg("  skipped\n")
            return True

        t_start = datetime.datetime.now()
        if os.path.exists(self.builddir):
            subprocess.run(["rm", "-rf", self.builddir])
        os.makedirs(self.confdir)
        os.symlink(self.buildset.siteconf, os.path.join(self.confdir, "site.conf"))
        kas_env = os.environ.copy()
        kas_env["KAS_WORK_DIR"] = self.buildset.workdir
        kas_env["KAS_BUILD_DIR"] = self.builddir
        kas_env["DL_DIR"] = self.dl_dir
        kas_env["SSTATE_DIR"] = self.sstate_dir

        kas_configs = [
            "build.yml",
            f"kas/release-{self.release}.yml",
            f"kas/machine-{self.machine}.yml",
            f"kas/kernel-{self.kernel}.yml",
        ]

        with open(self.logpath, "w") as f:
            rc = subprocess.run(
                [
                    "kas",
                    "build",
                    ":".join(kas_configs),
                ],
                stdout=f,
                stderr=f,
                env=kas_env,
            ).returncode
        if rc == 0:
            self.buildset.msg("  success ")
        else:
            self.buildset.msg("  failure ")
        t_stop = datetime.datetime.now()
        t_build = t_stop - t_start
        self.buildset.msg(f"in {pretty_timedelta(t_build)}\n")
        return rc == 0


class BuildSet:
    def __init__(self, releases, machines, kernels):
        self.releases = releases
        self.machines = machines
        self.kernels = kernels

    def __len__(self):
        return len(self.releases) * len(self.machines) * len(self.kernels)

    def __iter__(self):
        for release in self.releases:
            for machine in self.machines:
                for kernel in self.kernels:
                    yield Build(self, release, machine, kernel)

    def msg(self, msg):
        self.logfile.write(msg)
        print(msg, end="", flush=True)

    def prepare(self, args):
        self.workdir = args.workdir
        self.siteconf = args.siteconf
        self.logdir = os.path.join(self.workdir, "logs")
        os.makedirs(self.logdir, exist_ok=True)

        self.logpath = os.path.join(self.logdir, "build.log")
        self.logfile = open(self.logpath, "w")

    def build(self):
        count = len(self)
        had_error = False
        self.msg(f"Running {count} builds...\n")
        for i, build in enumerate(self):
            self.msg(f"[{i+1:03d}/{count:03d}] ")
            if not build.build():
                had_error = True

        if not had_error:
            self.msg("All succeeded.\n")
            return True
        else:
            self.msg("Failed!\n")
            return False


BUILDSETS = {
    "default": BuildSet(
        releases=("kirkstone", "master"),
        machines=("qemux86-64", "qemuriscv64", "qemuarm64"),
        kernels=("lts", "stable", "mainline"),
    ),
    "quick": BuildSet(
        releases=("master",),
        machines=("qemux86-64",),
        kernels=("lts", "stable", "mainline"),
    ),
    "extended": BuildSet(
        releases=("dunfell", "kirkstone", "master"),
        machines=(
            "qemux86-64",
            "qemuarm64",
            "qemuriscv64",
            "qemux86",
            "qemuarm",
            "qemuriscv32",
        ),
        kernels=("5.10", "6.1", "lts", "stable", "mainline"),
    ),
    "all": BuildSet(
        releases=("dunfell", "kirkstone", "nanbield", "master"),
        machines=(
            "qemux86-64",
            "qemuarm64",
            "qemuriscv64",
            "qemux86",
            "qemuarm",
            "qemuriscv32",
        ),
        kernels=(
            "4.19",
            "5.4",
            "5.10",
            "5.15",
            "6.1",
            "lts",
            "stable",
            "mainline",
        ),
    ),
    "riscv": BuildSet(
        releases=("kirkstone", "nanbield", "master"),
        machines=(
            "qemuriscv64",
            "qemuriscv32",
        ),
        kernels=(
            "6.1",
            "lts",
            "stable",
            "mainline",
        ),
    ),
}


def main():
    parser = argparse.ArgumentParser(
        description="meta-linux-mainline build script",
        epilog="Supported buildsets: " + ", ".join(BUILDSETS.keys()),
    )
    parser.add_argument(
        "-b", "--buildset", default="default", help="Select the set of builds to run"
    )
    parser.add_argument("-s", "--siteconf", help="Path to a local site.conf file")
    parser.add_argument(
        "-w", "--workdir", default=os.getcwd(), help="Path to build directory"
    )
    args = parser.parse_args()
    args.workdir = os.path.realpath(args.workdir)

    buildset = BUILDSETS[args.buildset]
    buildset.prepare(args)
    if buildset.build():
        sys.exit(0)
    else:
        sys.exit(1)


main()
