#! /bin/bash
# Copyright (C) 2021, meta-linux-mainline contributors
# SPDX-License-Identifier: MIT

if [[ $# -lt 3 ]]; then
    echo "Not enough arguments!"
    exit 1
fi

AUTOBUILD_POKYDIR="$1"
AUTOBUILD_DIR="$2"
shift 2

cd "$AUTOBUILD_POKYDIR" || exit 1
# shellcheck disable=SC1091
source oe-init-build-env "$AUTOBUILD_DIR"
echo "require conf/bblayers-auto.conf" >> conf/bblayers.conf
exec "$@"
