# Copyright (C) 2022, meta-linux-mainline contributors
# SPDX-License-Identifier: MIT

name: Update Yocto Project tracking branches
on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update branches
        run: |
          git push --force origin HEAD:master
          git push --force origin HEAD:wrynose
          git push --force origin HEAD:scarthgap
